/*
goid.gojekapi.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goid-gojek

import (
	"encoding/json"
)

// GenerateTokenRequest struct for GenerateTokenRequest
type GenerateTokenRequest struct {
	ClientId *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	Data *GoidTokenData `json:"data,omitempty"`
	GrantType *string `json:"grant_type,omitempty"`
	Scopes *[]interface{} `json:"scopes,omitempty"`
}

// NewGenerateTokenRequest instantiates a new GenerateTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateTokenRequest() *GenerateTokenRequest {
	this := GenerateTokenRequest{}
	var clientId string = "gojek:consumer:app"
	this.ClientId = &clientId
	var clientSecret string = "pGwQ7oi8bKqqwvid09UrjqpkMEHklb"
	this.ClientSecret = &clientSecret
	var grantType string = "otp"
	this.GrantType = &grantType
	return &this
}

// NewGenerateTokenRequestWithDefaults instantiates a new GenerateTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateTokenRequestWithDefaults() *GenerateTokenRequest {
	this := GenerateTokenRequest{}
	var clientId string = "gojek:consumer:app"
	this.ClientId = &clientId
	var clientSecret string = "pGwQ7oi8bKqqwvid09UrjqpkMEHklb"
	this.ClientSecret = &clientSecret
	var grantType string = "otp"
	this.GrantType = &grantType
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *GenerateTokenRequest) GetClientId() string {
	if o == nil || o.ClientId == nil {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTokenRequest) GetClientIdOk() (*string, bool) {
	if o == nil || o.ClientId == nil {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *GenerateTokenRequest) HasClientId() bool {
	if o != nil && o.ClientId != nil {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *GenerateTokenRequest) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *GenerateTokenRequest) GetClientSecret() string {
	if o == nil || o.ClientSecret == nil {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTokenRequest) GetClientSecretOk() (*string, bool) {
	if o == nil || o.ClientSecret == nil {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *GenerateTokenRequest) HasClientSecret() bool {
	if o != nil && o.ClientSecret != nil {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *GenerateTokenRequest) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GenerateTokenRequest) GetData() GoidTokenData {
	if o == nil || o.Data == nil {
		var ret GoidTokenData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTokenRequest) GetDataOk() (*GoidTokenData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GenerateTokenRequest) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GoidTokenData and assigns it to the Data field.
func (o *GenerateTokenRequest) SetData(v GoidTokenData) {
	o.Data = &v
}

// GetGrantType returns the GrantType field value if set, zero value otherwise.
func (o *GenerateTokenRequest) GetGrantType() string {
	if o == nil || o.GrantType == nil {
		var ret string
		return ret
	}
	return *o.GrantType
}

// GetGrantTypeOk returns a tuple with the GrantType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTokenRequest) GetGrantTypeOk() (*string, bool) {
	if o == nil || o.GrantType == nil {
		return nil, false
	}
	return o.GrantType, true
}

// HasGrantType returns a boolean if a field has been set.
func (o *GenerateTokenRequest) HasGrantType() bool {
	if o != nil && o.GrantType != nil {
		return true
	}

	return false
}

// SetGrantType gets a reference to the given string and assigns it to the GrantType field.
func (o *GenerateTokenRequest) SetGrantType(v string) {
	o.GrantType = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *GenerateTokenRequest) GetScopes() []interface{} {
	if o == nil || o.Scopes == nil {
		var ret []interface{}
		return ret
	}
	return *o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTokenRequest) GetScopesOk() (*[]interface{}, bool) {
	if o == nil || o.Scopes == nil {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *GenerateTokenRequest) HasScopes() bool {
	if o != nil && o.Scopes != nil {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []interface{} and assigns it to the Scopes field.
func (o *GenerateTokenRequest) SetScopes(v []interface{}) {
	o.Scopes = &v
}

func (o GenerateTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientId != nil {
		toSerialize["client_id"] = o.ClientId
	}
	if o.ClientSecret != nil {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.GrantType != nil {
		toSerialize["grant_type"] = o.GrantType
	}
	if o.Scopes != nil {
		toSerialize["scopes"] = o.Scopes
	}
	return json.Marshal(toSerialize)
}

type NullableGenerateTokenRequest struct {
	value *GenerateTokenRequest
	isSet bool
}

func (v NullableGenerateTokenRequest) Get() *GenerateTokenRequest {
	return v.value
}

func (v *NullableGenerateTokenRequest) Set(val *GenerateTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateTokenRequest(val *GenerateTokenRequest) *NullableGenerateTokenRequest {
	return &NullableGenerateTokenRequest{value: val, isSet: true}
}

func (v NullableGenerateTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


