/*
goid.gojekapi.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goid_gojek_go

import (
	"encoding/json"
)

// LoginRequestBody struct for LoginRequestBody
type LoginRequestBody struct {
	ClientId *string `json:"client_id,omitempty"`
	ClientSecret *string `json:"client_secret,omitempty"`
	CountryCode *string `json:"country_code,omitempty"`
	// possible value: otp_whatsapp, sms
	LoginType *string `json:"login_type,omitempty"`
	MagicLinkRef *string `json:"magic_link_ref,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
}

// NewLoginRequestBody instantiates a new LoginRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginRequestBody() *LoginRequestBody {
	this := LoginRequestBody{}
	var clientId string = "gojek:consumer:app"
	this.ClientId = &clientId
	var clientSecret string = "pGwQ7oi8bKqqwvid09UrjqpkMEHklb"
	this.ClientSecret = &clientSecret
	var countryCode string = "+62"
	this.CountryCode = &countryCode
	var loginType string = "otp_whatsapp"
	this.LoginType = &loginType
	return &this
}

// NewLoginRequestBodyWithDefaults instantiates a new LoginRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginRequestBodyWithDefaults() *LoginRequestBody {
	this := LoginRequestBody{}
	var clientId string = "gojek:consumer:app"
	this.ClientId = &clientId
	var clientSecret string = "pGwQ7oi8bKqqwvid09UrjqpkMEHklb"
	this.ClientSecret = &clientSecret
	var countryCode string = "+62"
	this.CountryCode = &countryCode
	var loginType string = "otp_whatsapp"
	this.LoginType = &loginType
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *LoginRequestBody) GetClientId() string {
	if o == nil || o.ClientId == nil {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetClientIdOk() (*string, bool) {
	if o == nil || o.ClientId == nil {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *LoginRequestBody) HasClientId() bool {
	if o != nil && o.ClientId != nil {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *LoginRequestBody) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *LoginRequestBody) GetClientSecret() string {
	if o == nil || o.ClientSecret == nil {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetClientSecretOk() (*string, bool) {
	if o == nil || o.ClientSecret == nil {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *LoginRequestBody) HasClientSecret() bool {
	if o != nil && o.ClientSecret != nil {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *LoginRequestBody) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *LoginRequestBody) GetCountryCode() string {
	if o == nil || o.CountryCode == nil {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetCountryCodeOk() (*string, bool) {
	if o == nil || o.CountryCode == nil {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *LoginRequestBody) HasCountryCode() bool {
	if o != nil && o.CountryCode != nil {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *LoginRequestBody) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetLoginType returns the LoginType field value if set, zero value otherwise.
func (o *LoginRequestBody) GetLoginType() string {
	if o == nil || o.LoginType == nil {
		var ret string
		return ret
	}
	return *o.LoginType
}

// GetLoginTypeOk returns a tuple with the LoginType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetLoginTypeOk() (*string, bool) {
	if o == nil || o.LoginType == nil {
		return nil, false
	}
	return o.LoginType, true
}

// HasLoginType returns a boolean if a field has been set.
func (o *LoginRequestBody) HasLoginType() bool {
	if o != nil && o.LoginType != nil {
		return true
	}

	return false
}

// SetLoginType gets a reference to the given string and assigns it to the LoginType field.
func (o *LoginRequestBody) SetLoginType(v string) {
	o.LoginType = &v
}

// GetMagicLinkRef returns the MagicLinkRef field value if set, zero value otherwise.
func (o *LoginRequestBody) GetMagicLinkRef() string {
	if o == nil || o.MagicLinkRef == nil {
		var ret string
		return ret
	}
	return *o.MagicLinkRef
}

// GetMagicLinkRefOk returns a tuple with the MagicLinkRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetMagicLinkRefOk() (*string, bool) {
	if o == nil || o.MagicLinkRef == nil {
		return nil, false
	}
	return o.MagicLinkRef, true
}

// HasMagicLinkRef returns a boolean if a field has been set.
func (o *LoginRequestBody) HasMagicLinkRef() bool {
	if o != nil && o.MagicLinkRef != nil {
		return true
	}

	return false
}

// SetMagicLinkRef gets a reference to the given string and assigns it to the MagicLinkRef field.
func (o *LoginRequestBody) SetMagicLinkRef(v string) {
	o.MagicLinkRef = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *LoginRequestBody) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginRequestBody) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *LoginRequestBody) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *LoginRequestBody) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

func (o LoginRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientId != nil {
		toSerialize["client_id"] = o.ClientId
	}
	if o.ClientSecret != nil {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if o.CountryCode != nil {
		toSerialize["country_code"] = o.CountryCode
	}
	if o.LoginType != nil {
		toSerialize["login_type"] = o.LoginType
	}
	if o.MagicLinkRef != nil {
		toSerialize["magic_link_ref"] = o.MagicLinkRef
	}
	if o.PhoneNumber != nil {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	return json.Marshal(toSerialize)
}

type NullableLoginRequestBody struct {
	value *LoginRequestBody
	isSet bool
}

func (v NullableLoginRequestBody) Get() *LoginRequestBody {
	return v.value
}

func (v *NullableLoginRequestBody) Set(val *LoginRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginRequestBody(val *LoginRequestBody) *NullableLoginRequestBody {
	return &NullableLoginRequestBody{value: val, isSet: true}
}

func (v NullableLoginRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


