/* tslint:disable */
/* eslint-disable */
/**
 * api.gojekapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    'message'?: string;
    /**
     * 
     * @type {InlineResponse200Customer}
     * @memberof InlineResponse200
     */
    'customer'?: InlineResponse200Customer;
}
/**
 * 
 * @export
 * @interface InlineResponse200Customer
 */
export interface InlineResponse200Customer {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200Customer
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'signed_up_country'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'country_code'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200Customer
     */
    'email_verified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'locale'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'locale_selection_type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200Customer
     */
    'facebook_connected'?: boolean;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse200Customer
     */
    'chat_id'?: object;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse200Customer
     */
    'chat_token'?: object;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200Customer
     */
    'created_at'?: string;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse200Customer
     */
    'bio'?: object;
    /**
     * 
     * @type {object}
     * @memberof InlineResponse200Customer
     */
    'profile_image_url'?: object;
}

/**
 * CustomerApi - axios parameter creator
 * @export
 */
export const CustomerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary GET customer
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerData: async (xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/gojek/v2/customer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xPlatform !== undefined && xPlatform !== null) {
                localVarHeaderParameter['x-platform'] = String(xPlatform);
            }

            if (gojekCountryCode !== undefined && gojekCountryCode !== null) {
                localVarHeaderParameter['gojek-country-code'] = String(gojekCountryCode);
            }

            if (xUniqueid !== undefined && xUniqueid !== null) {
                localVarHeaderParameter['x-uniqueid'] = String(xUniqueid);
            }

            if (xAppversion !== undefined && xAppversion !== null) {
                localVarHeaderParameter['x-appversion'] = String(xAppversion);
            }

            if (xAppid !== undefined && xAppid !== null) {
                localVarHeaderParameter['x-appid'] = String(xAppid);
            }

            if (xDeviceos !== undefined && xDeviceos !== null) {
                localVarHeaderParameter['x-deviceos'] = String(xDeviceos);
            }

            if (xUserType !== undefined && xUserType !== null) {
                localVarHeaderParameter['x-user-type'] = String(xUserType);
            }

            if (xPhonemake !== undefined && xPhonemake !== null) {
                localVarHeaderParameter['x-phonemake'] = String(xPhonemake);
            }

            if (xPhonemodel !== undefined && xPhonemodel !== null) {
                localVarHeaderParameter['x-phonemodel'] = String(xPhonemodel);
            }

            if (xPushtokentype !== undefined && xPushtokentype !== null) {
                localVarHeaderParameter['x-pushtokentype'] = String(xPushtokentype);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CustomerApi - functional programming interface
 * @export
 */
export const CustomerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CustomerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary GET customer
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCustomerData(xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomerData(xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CustomerApi - factory interface
 * @export
 */
export const CustomerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustomerApiFp(configuration)
    return {
        /**
         * 
         * @summary GET customer
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerData(xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.getCustomerData(xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCustomerData operation in CustomerApi.
 * @export
 * @interface CustomerApiGetCustomerDataRequest
 */
export interface CustomerApiGetCustomerDataRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPlatform?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly gojekCountryCode?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xUniqueid?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xAppversion?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xAppid?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xDeviceos?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xUserType?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPhonemake?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPhonemodel?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPushtokentype?: string
}

/**
 * CustomerApi - object-oriented interface
 * @export
 * @class CustomerApi
 * @extends {BaseAPI}
 */
export class CustomerApi extends BaseAPI {
    /**
     * 
     * @summary GET customer
     * @param {CustomerApiGetCustomerDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomerApi
     */
    public getCustomerData(requestParameters: CustomerApiGetCustomerDataRequest = {}, options?: AxiosRequestConfig) {
        return CustomerApiFp(this.configuration).getCustomerData(requestParameters.xPlatform, requestParameters.gojekCountryCode, requestParameters.xUniqueid, requestParameters.xAppversion, requestParameters.xAppid, requestParameters.xDeviceos, requestParameters.xUserType, requestParameters.xPhonemake, requestParameters.xPhonemodel, requestParameters.xPushtokentype, options).then((request) => request(this.axios, this.basePath));
    }
}


