/* tslint:disable */
/* eslint-disable */
/**
 * api.gojekapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface CancelBookingResponse
 */
export interface CancelBookingResponse {
    /**
     * 
     * @type {string}
     * @memberof CancelBookingResponse
     */
    'order_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof CancelBookingResponse
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CancelBookingResponse
     */
    'success'?: boolean;
}
/**
 * 
 * @export
 * @interface GetCustomerDataResponse
 */
export interface GetCustomerDataResponse {
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponse
     */
    'message'?: string;
    /**
     * 
     * @type {GetCustomerDataResponseCustomer}
     * @memberof GetCustomerDataResponse
     */
    'customer'?: GetCustomerDataResponseCustomer;
}
/**
 * 
 * @export
 * @interface GetCustomerDataResponseCustomer
 */
export interface GetCustomerDataResponseCustomer {
    /**
     * 
     * @type {number}
     * @memberof GetCustomerDataResponseCustomer
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'signed_up_country'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'country_code'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetCustomerDataResponseCustomer
     */
    'email_verified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'locale'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'locale_selection_type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetCustomerDataResponseCustomer
     */
    'facebook_connected'?: boolean;
    /**
     * 
     * @type {object}
     * @memberof GetCustomerDataResponseCustomer
     */
    'chat_id'?: object;
    /**
     * 
     * @type {object}
     * @memberof GetCustomerDataResponseCustomer
     */
    'chat_token'?: object;
    /**
     * 
     * @type {string}
     * @memberof GetCustomerDataResponseCustomer
     */
    'created_at'?: string;
    /**
     * 
     * @type {object}
     * @memberof GetCustomerDataResponseCustomer
     */
    'bio'?: object;
    /**
     * 
     * @type {object}
     * @memberof GetCustomerDataResponseCustomer
     */
    'profile_image_url'?: object;
}
/**
 * 
 * @export
 * @interface GetDropoffSpotsResponse
 */
export interface GetDropoffSpotsResponse {
    /**
     * 
     * @type {GetDropoffSpotsResponseData}
     * @memberof GetDropoffSpotsResponse
     */
    'data'?: GetDropoffSpotsResponseData;
}
/**
 * 
 * @export
 * @interface GetDropoffSpotsResponseData
 */
export interface GetDropoffSpotsResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetDropoffSpotsResponseData
     */
    'type'?: string;
    /**
     * 
     * @type {GetDropoffSpotsResponseDataSourceLocation}
     * @memberof GetDropoffSpotsResponseData
     */
    'source_location'?: GetDropoffSpotsResponseDataSourceLocation;
    /**
     * 
     * @type {Array<object>}
     * @memberof GetDropoffSpotsResponseData
     */
    'places'?: Array<object>;
}
/**
 * 
 * @export
 * @interface GetDropoffSpotsResponseDataSourceLocation
 */
export interface GetDropoffSpotsResponseDataSourceLocation {
    /**
     * 
     * @type {string}
     * @memberof GetDropoffSpotsResponseDataSourceLocation
     */
    'place_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDropoffSpotsResponseDataSourceLocation
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDropoffSpotsResponseDataSourceLocation
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetDropoffSpotsResponseDataSourceLocation
     */
    'image_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetDropoffSpotsResponseDataSourceLocation
     */
    'suggested_visibility_radius'?: number;
}
/**
 * 
 * @export
 * @interface GetPickupSpotsResponse
 */
export interface GetPickupSpotsResponse {
    /**
     * 
     * @type {GetPickupSpotsResponseData}
     * @memberof GetPickupSpotsResponse
     */
    'data'?: GetPickupSpotsResponseData;
}
/**
 * 
 * @export
 * @interface GetPickupSpotsResponseData
 */
export interface GetPickupSpotsResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetPickupSpotsResponseData
     */
    'type'?: string;
    /**
     * 
     * @type {GetPickupSpotsResponseDataSourceLocation}
     * @memberof GetPickupSpotsResponseData
     */
    'source_location'?: GetPickupSpotsResponseDataSourceLocation;
    /**
     * 
     * @type {Array<GetPickupSpotsResponseDataPlaces>}
     * @memberof GetPickupSpotsResponseData
     */
    'places'?: Array<GetPickupSpotsResponseDataPlaces>;
}
/**
 * 
 * @export
 * @interface GetPickupSpotsResponseDataPlaces
 */
export interface GetPickupSpotsResponseDataPlaces {
    /**
     * 
     * @type {string}
     * @memberof GetPickupSpotsResponseDataPlaces
     */
    'place_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPickupSpotsResponseDataPlaces
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPickupSpotsResponseDataPlaces
     */
    'address'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetPickupSpotsResponseDataPlaces
     */
    'latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPickupSpotsResponseDataPlaces
     */
    'longitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPickupSpotsResponseDataPlaces
     */
    'distance_from_origin'?: number;
}
/**
 * 
 * @export
 * @interface GetPickupSpotsResponseDataSourceLocation
 */
export interface GetPickupSpotsResponseDataSourceLocation {
    /**
     * 
     * @type {string}
     * @memberof GetPickupSpotsResponseDataSourceLocation
     */
    'place_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPickupSpotsResponseDataSourceLocation
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPickupSpotsResponseDataSourceLocation
     */
    'address'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetPickupSpotsResponseDataSourceLocation
     */
    'suggested_visibility_radius'?: number;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponse
 */
export interface GetTransportEstimateResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetTransportEstimateResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {GetTransportEstimateResponseData}
     * @memberof GetTransportEstimateResponse
     */
    'data'?: GetTransportEstimateResponseData;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseData
 */
export interface GetTransportEstimateResponseData {
    /**
     * 
     * @type {GetTransportEstimateResponseDataOriginServiceArea}
     * @memberof GetTransportEstimateResponseData
     */
    'origin_service_area'?: GetTransportEstimateResponseDataOriginServiceArea;
    /**
     * 
     * @type {GetTransportEstimateResponseDataOriginServiceArea}
     * @memberof GetTransportEstimateResponseData
     */
    'destination_service_area'?: GetTransportEstimateResponseDataOriginServiceArea;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseData
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseData
     */
    'base_token'?: string;
    /**
     * 
     * @type {GetTransportEstimateResponseDataBusinessBooking}
     * @memberof GetTransportEstimateResponseData
     */
    'business_booking'?: GetTransportEstimateResponseDataBusinessBooking;
    /**
     * 
     * @type {Array<GetTransportEstimateResponseDataServiceTypes>}
     * @memberof GetTransportEstimateResponseData
     */
    'service_types'?: Array<GetTransportEstimateResponseDataServiceTypes>;
    /**
     * 
     * @type {GetTransportEstimateResponseDataPromotion}
     * @memberof GetTransportEstimateResponseData
     */
    'promotion'?: GetTransportEstimateResponseDataPromotion;
    /**
     * 
     * @type {GetTransportEstimateResponseDataDisclaimer}
     * @memberof GetTransportEstimateResponseData
     */
    'disclaimer'?: GetTransportEstimateResponseDataDisclaimer;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseData
     */
    'voucher_flow'?: string;
    /**
     * 
     * @type {GetTransportEstimateResponseDataUpsell}
     * @memberof GetTransportEstimateResponseData
     */
    'upsell'?: GetTransportEstimateResponseDataUpsell;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataAllocationStrategy
 */
export interface GetTransportEstimateResponseDataAllocationStrategy {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataAllocationStrategy
     */
    'type'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataBusinessBooking
 */
export interface GetTransportEstimateResponseDataBusinessBooking {
    /**
     * 
     * @type {boolean}
     * @memberof GetTransportEstimateResponseDataBusinessBooking
     */
    'corporate_billing_applicable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetTransportEstimateResponseDataBusinessBooking
     */
    'trip_profile_widget_enabled'?: boolean;
    /**
     * 
     * @type {GetTransportEstimateResponseDataBusinessBookingDescription}
     * @memberof GetTransportEstimateResponseDataBusinessBooking
     */
    'description'?: GetTransportEstimateResponseDataBusinessBookingDescription;
    /**
     * 
     * @type {GetTransportEstimateResponseDataBusinessBookingOnboarding}
     * @memberof GetTransportEstimateResponseDataBusinessBooking
     */
    'onboarding'?: GetTransportEstimateResponseDataBusinessBookingOnboarding;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataBusinessBookingDescription
 */
export interface GetTransportEstimateResponseDataBusinessBookingDescription {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingDescription
     */
    'heading'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingDescription
     */
    'subheading'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingDescription
     */
    'cta_text'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataBusinessBookingOnboarding
 */
export interface GetTransportEstimateResponseDataBusinessBookingOnboarding {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingOnboarding
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingOnboarding
     */
    'subtitle'?: string;
    /**
     * 
     * @type {Array<GetTransportEstimateResponseDataBusinessBookingOnboardingTerms>}
     * @memberof GetTransportEstimateResponseDataBusinessBookingOnboarding
     */
    'terms'?: Array<GetTransportEstimateResponseDataBusinessBookingOnboardingTerms>;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingOnboarding
     */
    'cta_text'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataBusinessBookingOnboardingTerms
 */
export interface GetTransportEstimateResponseDataBusinessBookingOnboardingTerms {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingOnboardingTerms
     */
    'icon_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataBusinessBookingOnboardingTerms
     */
    'text'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataDisclaimer
 */
export interface GetTransportEstimateResponseDataDisclaimer {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataDisclaimer
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataInsuranceDetails
 */
export interface GetTransportEstimateResponseDataInsuranceDetails {
    /**
     * 
     * @type {boolean}
     * @memberof GetTransportEstimateResponseDataInsuranceDetails
     */
    'trip_insured'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataInsuranceDetails
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataInsuranceDetails
     */
    'cta_link'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataOriginServiceArea
 */
export interface GetTransportEstimateResponseDataOriginServiceArea {
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataOriginServiceArea
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataOriginServiceArea
     */
    'country_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataOriginServiceArea
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataOriginServiceArea
     */
    'tz_name'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataPaymentMethods
 */
export interface GetTransportEstimateResponseDataPaymentMethods {
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'price_with_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'price_without_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'min_price_without_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'max_price_without_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'min_price_with_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'max_price_with_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'surge'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'base_fare_with_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'base_fare_without_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'platform_fee'?: number;
    /**
     * 
     * @type {GetTransportEstimateResponseDataPriceRange}
     * @memberof GetTransportEstimateResponseDataPaymentMethods
     */
    'price_range'?: GetTransportEstimateResponseDataPriceRange;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataPriceRange
 */
export interface GetTransportEstimateResponseDataPriceRange {
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPriceRange
     */
    'subtract_with_voucher'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPriceRange
     */
    'subtract_without_voucher'?: number;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataPromotion
 */
export interface GetTransportEstimateResponseDataPromotion {
    /**
     * 
     * @type {GetTransportEstimateResponseDataPromotionBubble}
     * @memberof GetTransportEstimateResponseDataPromotion
     */
    'bubble'?: GetTransportEstimateResponseDataPromotionBubble;
    /**
     * 
     * @type {Array<GetTransportEstimateResponseDataPromotionBubble>}
     * @memberof GetTransportEstimateResponseDataPromotion
     */
    'bubbles'?: Array<GetTransportEstimateResponseDataPromotionBubble>;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataPromotionBubble
 */
export interface GetTransportEstimateResponseDataPromotionBubble {
    /**
     * 
     * @type {Array<GetTransportEstimateResponseDataPromotionBubblePromotionDetails>}
     * @memberof GetTransportEstimateResponseDataPromotionBubble
     */
    'promotion_details'?: Array<GetTransportEstimateResponseDataPromotionBubblePromotionDetails>;
    /**
     * 
     * @type {GetTransportEstimateResponseDataPromotionBubbleExperimentDetail}
     * @memberof GetTransportEstimateResponseDataPromotionBubble
     */
    'experiment_detail'?: GetTransportEstimateResponseDataPromotionBubbleExperimentDetail;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataPromotionBubbleExperimentDetail
 */
export interface GetTransportEstimateResponseDataPromotionBubbleExperimentDetail {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubbleExperimentDetail
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubbleExperimentDetail
     */
    'variant'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataPromotionBubblePromotionDetails
 */
export interface GetTransportEstimateResponseDataPromotionBubblePromotionDetails {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubblePromotionDetails
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubblePromotionDetails
     */
    'cta_link'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubblePromotionDetails
     */
    'cta_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubblePromotionDetails
     */
    'payment_option'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataPromotionBubblePromotionDetails
     */
    'service_type'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubblePromotionDetails
     */
    'bubble_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataPromotionBubblePromotionDetails
     */
    'text_type'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataRoute
 */
export interface GetTransportEstimateResponseDataRoute {
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataRoute
     */
    'eta'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataRoute
     */
    'distance_in_meters'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataRoute
     */
    'polyline'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataRoute
     */
    'route_type'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataServiceTypeDetails
 */
export interface GetTransportEstimateResponseDataServiceTypeDetails {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataServiceTypeDetails
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetTransportEstimateResponseDataServiceTypeDetails
     */
    'should_show_benefits'?: boolean;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataServiceTypes
 */
export interface GetTransportEstimateResponseDataServiceTypes {
    /**
     * 
     * @type {GetTransportEstimateResponseDataRoute}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'route'?: GetTransportEstimateResponseDataRoute;
    /**
     * 
     * @type {number}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'id'?: number;
    /**
     * 
     * @type {GetTransportEstimateResponseDataServiceTypeDetails}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'service_type_details'?: GetTransportEstimateResponseDataServiceTypeDetails;
    /**
     * 
     * @type {GetTransportEstimateResponseDataInsuranceDetails}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'insurance_details'?: GetTransportEstimateResponseDataInsuranceDetails;
    /**
     * 
     * @type {GetTransportEstimateResponseDataAllocationStrategy}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'allocation_strategy'?: GetTransportEstimateResponseDataAllocationStrategy;
    /**
     * 
     * @type {Array<GetTransportEstimateResponseDataAllocationStrategy>}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'allocation_strategies'?: Array<GetTransportEstimateResponseDataAllocationStrategy>;
    /**
     * 
     * @type {Array<GetTransportEstimateResponseDataPaymentMethods>}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'payment_methods'?: Array<GetTransportEstimateResponseDataPaymentMethods>;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'pricing_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'pickup_eta'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'applicable_upsell'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'service_provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataServiceTypes
     */
    'success'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataUpsell
 */
export interface GetTransportEstimateResponseDataUpsell {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsell
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsell
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsell
     */
    'disclaimer'?: string;
    /**
     * 
     * @type {Array<GetTransportEstimateResponseDataUpsellTypes>}
     * @memberof GetTransportEstimateResponseDataUpsell
     */
    'types'?: Array<GetTransportEstimateResponseDataUpsellTypes>;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataUpsellBadge
 */
export interface GetTransportEstimateResponseDataUpsellBadge {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsellBadge
     */
    'title'?: string;
}
/**
 * 
 * @export
 * @interface GetTransportEstimateResponseDataUpsellTypes
 */
export interface GetTransportEstimateResponseDataUpsellTypes {
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'opt_in'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'price'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'product_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'product_code'?: string;
    /**
     * 
     * @type {GetTransportEstimateResponseDataUpsellBadge}
     * @memberof GetTransportEstimateResponseDataUpsellTypes
     */
    'badge'?: GetTransportEstimateResponseDataUpsellBadge;
}

/**
 * CustomerApi - axios parameter creator
 * @export
 */
export const CustomerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary GET customer
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerData: async (xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/gojek/v2/customer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xPlatform !== undefined && xPlatform !== null) {
                localVarHeaderParameter['x-platform'] = String(xPlatform);
            }

            if (gojekCountryCode !== undefined && gojekCountryCode !== null) {
                localVarHeaderParameter['gojek-country-code'] = String(gojekCountryCode);
            }

            if (xUniqueid !== undefined && xUniqueid !== null) {
                localVarHeaderParameter['x-uniqueid'] = String(xUniqueid);
            }

            if (xAppversion !== undefined && xAppversion !== null) {
                localVarHeaderParameter['x-appversion'] = String(xAppversion);
            }

            if (xAppid !== undefined && xAppid !== null) {
                localVarHeaderParameter['x-appid'] = String(xAppid);
            }

            if (xDeviceos !== undefined && xDeviceos !== null) {
                localVarHeaderParameter['x-deviceos'] = String(xDeviceos);
            }

            if (xUserType !== undefined && xUserType !== null) {
                localVarHeaderParameter['x-user-type'] = String(xUserType);
            }

            if (xPhonemake !== undefined && xPhonemake !== null) {
                localVarHeaderParameter['x-phonemake'] = String(xPhonemake);
            }

            if (xPhonemodel !== undefined && xPhonemodel !== null) {
                localVarHeaderParameter['x-phonemodel'] = String(xPhonemodel);
            }

            if (xPushtokentype !== undefined && xPushtokentype !== null) {
                localVarHeaderParameter['x-pushtokentype'] = String(xPushtokentype);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CustomerApi - functional programming interface
 * @export
 */
export const CustomerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CustomerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary GET customer
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCustomerData(xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetCustomerDataResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomerData(xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CustomerApi - factory interface
 * @export
 */
export const CustomerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustomerApiFp(configuration)
    return {
        /**
         * 
         * @summary GET customer
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerData(xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, options?: any): AxiosPromise<GetCustomerDataResponse> {
            return localVarFp.getCustomerData(xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCustomerData operation in CustomerApi.
 * @export
 * @interface CustomerApiGetCustomerDataRequest
 */
export interface CustomerApiGetCustomerDataRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPlatform?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly gojekCountryCode?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xUniqueid?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xAppversion?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xAppid?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xDeviceos?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xUserType?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPhonemake?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPhonemodel?: string

    /**
     * 
     * @type {string}
     * @memberof CustomerApiGetCustomerData
     */
    readonly xPushtokentype?: string
}

/**
 * CustomerApi - object-oriented interface
 * @export
 * @class CustomerApi
 * @extends {BaseAPI}
 */
export class CustomerApi extends BaseAPI {
    /**
     * 
     * @summary GET customer
     * @param {CustomerApiGetCustomerDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomerApi
     */
    public getCustomerData(requestParameters: CustomerApiGetCustomerDataRequest = {}, options?: AxiosRequestConfig) {
        return CustomerApiFp(this.configuration).getCustomerData(requestParameters.xPlatform, requestParameters.gojekCountryCode, requestParameters.xUniqueid, requestParameters.xAppversion, requestParameters.xAppid, requestParameters.xDeviceos, requestParameters.xUserType, requestParameters.xPhonemake, requestParameters.xPhonemodel, requestParameters.xPushtokentype, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * TransportApi - axios parameter creator
 * @export
 */
export const TransportApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * cancel booking
         * @summary Cancel booking
         * @param {string} bookingId 
         * @param {number} cancelReasonId 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBooking: async (bookingId: string, cancelReasonId: number, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bookingId' is not null or undefined
            assertParamExists('cancelBooking', 'bookingId', bookingId)
            // verify required parameter 'cancelReasonId' is not null or undefined
            assertParamExists('cancelBooking', 'cancelReasonId', cancelReasonId)
            const localVarPath = `/v3/bookings/{booking_id}/cancel`
                .replace(`{${"booking_id"}}`, encodeURIComponent(String(bookingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication bearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xPlatform !== undefined && xPlatform !== null) {
                localVarHeaderParameter['x-platform'] = String(xPlatform);
            }

            if (gojekCountryCode !== undefined && gojekCountryCode !== null) {
                localVarHeaderParameter['gojek-country-code'] = String(gojekCountryCode);
            }

            if (xUniqueid !== undefined && xUniqueid !== null) {
                localVarHeaderParameter['x-uniqueid'] = String(xUniqueid);
            }

            if (xAppversion !== undefined && xAppversion !== null) {
                localVarHeaderParameter['x-appversion'] = String(xAppversion);
            }

            if (xAppid !== undefined && xAppid !== null) {
                localVarHeaderParameter['x-appid'] = String(xAppid);
            }

            if (xDeviceos !== undefined && xDeviceos !== null) {
                localVarHeaderParameter['x-deviceos'] = String(xDeviceos);
            }

            if (xUserType !== undefined && xUserType !== null) {
                localVarHeaderParameter['x-user-type'] = String(xUserType);
            }

            if (xPhonemake !== undefined && xPhonemake !== null) {
                localVarHeaderParameter['x-phonemake'] = String(xPhonemake);
            }

            if (xPhonemodel !== undefined && xPhonemodel !== null) {
                localVarHeaderParameter['x-phonemodel'] = String(xPhonemodel);
            }

            if (xPushtokentype !== undefined && xPushtokentype !== null) {
                localVarHeaderParameter['x-pushtokentype'] = String(xPushtokentype);
            }

            if (xSessionId !== undefined && xSessionId !== null) {
                localVarHeaderParameter['x-session-id'] = String(xSessionId);
            }


            if (cancelReasonId !== undefined) { 
                localVarFormParams.set('cancel_reason_id', cancelReasonId as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET dropoff spots
         * @param {string} location 
         * @param {number} serviceType 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDropoffSpots: async (location: string, serviceType: number, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'location' is not null or undefined
            assertParamExists('getDropoffSpots', 'location', location)
            // verify required parameter 'serviceType' is not null or undefined
            assertParamExists('getDropoffSpots', 'serviceType', serviceType)
            const localVarPath = `/v1/dropoff-spots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (location !== undefined) {
                localVarQueryParameter['location'] = location;
            }

            if (serviceType !== undefined) {
                localVarQueryParameter['service_type'] = serviceType;
            }

            if (xPlatform !== undefined && xPlatform !== null) {
                localVarHeaderParameter['x-platform'] = String(xPlatform);
            }

            if (gojekCountryCode !== undefined && gojekCountryCode !== null) {
                localVarHeaderParameter['gojek-country-code'] = String(gojekCountryCode);
            }

            if (xUniqueid !== undefined && xUniqueid !== null) {
                localVarHeaderParameter['x-uniqueid'] = String(xUniqueid);
            }

            if (xAppversion !== undefined && xAppversion !== null) {
                localVarHeaderParameter['x-appversion'] = String(xAppversion);
            }

            if (xAppid !== undefined && xAppid !== null) {
                localVarHeaderParameter['x-appid'] = String(xAppid);
            }

            if (xDeviceos !== undefined && xDeviceos !== null) {
                localVarHeaderParameter['x-deviceos'] = String(xDeviceos);
            }

            if (xUserType !== undefined && xUserType !== null) {
                localVarHeaderParameter['x-user-type'] = String(xUserType);
            }

            if (xPhonemake !== undefined && xPhonemake !== null) {
                localVarHeaderParameter['x-phonemake'] = String(xPhonemake);
            }

            if (xPhonemodel !== undefined && xPhonemodel !== null) {
                localVarHeaderParameter['x-phonemodel'] = String(xPhonemodel);
            }

            if (xPushtokentype !== undefined && xPushtokentype !== null) {
                localVarHeaderParameter['x-pushtokentype'] = String(xPushtokentype);
            }

            if (xSessionId !== undefined && xSessionId !== null) {
                localVarHeaderParameter['x-session-id'] = String(xSessionId);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET pickup spots
         * @param {string} location 
         * @param {number} serviceType 
         * @param {string} source 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPickupSpots: async (location: string, serviceType: number, source: string, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'location' is not null or undefined
            assertParamExists('getPickupSpots', 'location', location)
            // verify required parameter 'serviceType' is not null or undefined
            assertParamExists('getPickupSpots', 'serviceType', serviceType)
            // verify required parameter 'source' is not null or undefined
            assertParamExists('getPickupSpots', 'source', source)
            const localVarPath = `/v1/pickup-spots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (location !== undefined) {
                localVarQueryParameter['location'] = location;
            }

            if (serviceType !== undefined) {
                localVarQueryParameter['service_type'] = serviceType;
            }

            if (source !== undefined) {
                localVarQueryParameter['source'] = source;
            }

            if (xPlatform !== undefined && xPlatform !== null) {
                localVarHeaderParameter['x-platform'] = String(xPlatform);
            }

            if (gojekCountryCode !== undefined && gojekCountryCode !== null) {
                localVarHeaderParameter['gojek-country-code'] = String(gojekCountryCode);
            }

            if (xUniqueid !== undefined && xUniqueid !== null) {
                localVarHeaderParameter['x-uniqueid'] = String(xUniqueid);
            }

            if (xAppversion !== undefined && xAppversion !== null) {
                localVarHeaderParameter['x-appversion'] = String(xAppversion);
            }

            if (xAppid !== undefined && xAppid !== null) {
                localVarHeaderParameter['x-appid'] = String(xAppid);
            }

            if (xDeviceos !== undefined && xDeviceos !== null) {
                localVarHeaderParameter['x-deviceos'] = String(xDeviceos);
            }

            if (xUserType !== undefined && xUserType !== null) {
                localVarHeaderParameter['x-user-type'] = String(xUserType);
            }

            if (xPhonemake !== undefined && xPhonemake !== null) {
                localVarHeaderParameter['x-phonemake'] = String(xPhonemake);
            }

            if (xPhonemodel !== undefined && xPhonemodel !== null) {
                localVarHeaderParameter['x-phonemodel'] = String(xPhonemodel);
            }

            if (xPushtokentype !== undefined && xPushtokentype !== null) {
                localVarHeaderParameter['x-pushtokentype'] = String(xPushtokentype);
            }

            if (xSessionId !== undefined && xSessionId !== null) {
                localVarHeaderParameter['x-session-id'] = String(xSessionId);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET transport estimate
         * @param {boolean} sendPrioritisedOrder 
         * @param {number} userSelectedServiceType 
         * @param {string} waypoints pickup coordinate | dropoff coodinate. Example: -6.188912,106.738236|-6.184608,106.736176
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransportEstimate: async (sendPrioritisedOrder: boolean, userSelectedServiceType: number, waypoints: string, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendPrioritisedOrder' is not null or undefined
            assertParamExists('getTransportEstimate', 'sendPrioritisedOrder', sendPrioritisedOrder)
            // verify required parameter 'userSelectedServiceType' is not null or undefined
            assertParamExists('getTransportEstimate', 'userSelectedServiceType', userSelectedServiceType)
            // verify required parameter 'waypoints' is not null or undefined
            assertParamExists('getTransportEstimate', 'waypoints', waypoints)
            const localVarPath = `/transport/v1/estimate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (sendPrioritisedOrder !== undefined) {
                localVarQueryParameter['send_prioritised_order'] = sendPrioritisedOrder;
            }

            if (userSelectedServiceType !== undefined) {
                localVarQueryParameter['user_selected_service_type'] = userSelectedServiceType;
            }

            if (waypoints !== undefined) {
                localVarQueryParameter['waypoints'] = waypoints;
            }

            if (xPlatform !== undefined && xPlatform !== null) {
                localVarHeaderParameter['x-platform'] = String(xPlatform);
            }

            if (gojekCountryCode !== undefined && gojekCountryCode !== null) {
                localVarHeaderParameter['gojek-country-code'] = String(gojekCountryCode);
            }

            if (xUniqueid !== undefined && xUniqueid !== null) {
                localVarHeaderParameter['x-uniqueid'] = String(xUniqueid);
            }

            if (xAppversion !== undefined && xAppversion !== null) {
                localVarHeaderParameter['x-appversion'] = String(xAppversion);
            }

            if (xAppid !== undefined && xAppid !== null) {
                localVarHeaderParameter['x-appid'] = String(xAppid);
            }

            if (xDeviceos !== undefined && xDeviceos !== null) {
                localVarHeaderParameter['x-deviceos'] = String(xDeviceos);
            }

            if (xUserType !== undefined && xUserType !== null) {
                localVarHeaderParameter['x-user-type'] = String(xUserType);
            }

            if (xPhonemake !== undefined && xPhonemake !== null) {
                localVarHeaderParameter['x-phonemake'] = String(xPhonemake);
            }

            if (xPhonemodel !== undefined && xPhonemodel !== null) {
                localVarHeaderParameter['x-phonemodel'] = String(xPhonemodel);
            }

            if (xPushtokentype !== undefined && xPushtokentype !== null) {
                localVarHeaderParameter['x-pushtokentype'] = String(xPushtokentype);
            }

            if (xSessionId !== undefined && xSessionId !== null) {
                localVarHeaderParameter['x-session-id'] = String(xSessionId);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransportApi - functional programming interface
 * @export
 */
export const TransportApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransportApiAxiosParamCreator(configuration)
    return {
        /**
         * cancel booking
         * @summary Cancel booking
         * @param {string} bookingId 
         * @param {number} cancelReasonId 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelBooking(bookingId: string, cancelReasonId: number, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelBookingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelBooking(bookingId, cancelReasonId, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary GET dropoff spots
         * @param {string} location 
         * @param {number} serviceType 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDropoffSpots(location: string, serviceType: number, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetDropoffSpotsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDropoffSpots(location, serviceType, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary GET pickup spots
         * @param {string} location 
         * @param {number} serviceType 
         * @param {string} source 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPickupSpots(location: string, serviceType: number, source: string, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetPickupSpotsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPickupSpots(location, serviceType, source, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary GET transport estimate
         * @param {boolean} sendPrioritisedOrder 
         * @param {number} userSelectedServiceType 
         * @param {string} waypoints pickup coordinate | dropoff coodinate. Example: -6.188912,106.738236|-6.184608,106.736176
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransportEstimate(sendPrioritisedOrder: boolean, userSelectedServiceType: number, waypoints: string, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetTransportEstimateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransportEstimate(sendPrioritisedOrder, userSelectedServiceType, waypoints, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TransportApi - factory interface
 * @export
 */
export const TransportApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransportApiFp(configuration)
    return {
        /**
         * cancel booking
         * @summary Cancel booking
         * @param {string} bookingId 
         * @param {number} cancelReasonId 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelBooking(bookingId: string, cancelReasonId: number, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: any): AxiosPromise<CancelBookingResponse> {
            return localVarFp.cancelBooking(bookingId, cancelReasonId, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET dropoff spots
         * @param {string} location 
         * @param {number} serviceType 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDropoffSpots(location: string, serviceType: number, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: any): AxiosPromise<GetDropoffSpotsResponse> {
            return localVarFp.getDropoffSpots(location, serviceType, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET pickup spots
         * @param {string} location 
         * @param {number} serviceType 
         * @param {string} source 
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPickupSpots(location: string, serviceType: number, source: string, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: any): AxiosPromise<GetPickupSpotsResponse> {
            return localVarFp.getPickupSpots(location, serviceType, source, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET transport estimate
         * @param {boolean} sendPrioritisedOrder 
         * @param {number} userSelectedServiceType 
         * @param {string} waypoints pickup coordinate | dropoff coodinate. Example: -6.188912,106.738236|-6.184608,106.736176
         * @param {string} [xPlatform] 
         * @param {string} [gojekCountryCode] 
         * @param {string} [xUniqueid] 
         * @param {string} [xAppversion] 
         * @param {string} [xAppid] 
         * @param {string} [xDeviceos] 
         * @param {string} [xUserType] 
         * @param {string} [xPhonemake] 
         * @param {string} [xPhonemodel] 
         * @param {string} [xPushtokentype] 
         * @param {string} [xSessionId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransportEstimate(sendPrioritisedOrder: boolean, userSelectedServiceType: number, waypoints: string, xPlatform?: string, gojekCountryCode?: string, xUniqueid?: string, xAppversion?: string, xAppid?: string, xDeviceos?: string, xUserType?: string, xPhonemake?: string, xPhonemodel?: string, xPushtokentype?: string, xSessionId?: string, options?: any): AxiosPromise<GetTransportEstimateResponse> {
            return localVarFp.getTransportEstimate(sendPrioritisedOrder, userSelectedServiceType, waypoints, xPlatform, gojekCountryCode, xUniqueid, xAppversion, xAppid, xDeviceos, xUserType, xPhonemake, xPhonemodel, xPushtokentype, xSessionId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cancelBooking operation in TransportApi.
 * @export
 * @interface TransportApiCancelBookingRequest
 */
export interface TransportApiCancelBookingRequest {
    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly bookingId: string

    /**
     * 
     * @type {number}
     * @memberof TransportApiCancelBooking
     */
    readonly cancelReasonId: number

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xPlatform?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly gojekCountryCode?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xUniqueid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xAppversion?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xAppid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xDeviceos?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xUserType?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xPhonemake?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xPhonemodel?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xPushtokentype?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiCancelBooking
     */
    readonly xSessionId?: string
}

/**
 * Request parameters for getDropoffSpots operation in TransportApi.
 * @export
 * @interface TransportApiGetDropoffSpotsRequest
 */
export interface TransportApiGetDropoffSpotsRequest {
    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly location: string

    /**
     * 
     * @type {number}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly serviceType: number

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xPlatform?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly gojekCountryCode?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xUniqueid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xAppversion?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xAppid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xDeviceos?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xUserType?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xPhonemake?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xPhonemodel?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xPushtokentype?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetDropoffSpots
     */
    readonly xSessionId?: string
}

/**
 * Request parameters for getPickupSpots operation in TransportApi.
 * @export
 * @interface TransportApiGetPickupSpotsRequest
 */
export interface TransportApiGetPickupSpotsRequest {
    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly location: string

    /**
     * 
     * @type {number}
     * @memberof TransportApiGetPickupSpots
     */
    readonly serviceType: number

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly source: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xPlatform?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly gojekCountryCode?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xUniqueid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xAppversion?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xAppid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xDeviceos?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xUserType?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xPhonemake?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xPhonemodel?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xPushtokentype?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetPickupSpots
     */
    readonly xSessionId?: string
}

/**
 * Request parameters for getTransportEstimate operation in TransportApi.
 * @export
 * @interface TransportApiGetTransportEstimateRequest
 */
export interface TransportApiGetTransportEstimateRequest {
    /**
     * 
     * @type {boolean}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly sendPrioritisedOrder: boolean

    /**
     * 
     * @type {number}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly userSelectedServiceType: number

    /**
     * pickup coordinate | dropoff coodinate. Example: -6.188912,106.738236|-6.184608,106.736176
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly waypoints: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xPlatform?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly gojekCountryCode?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xUniqueid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xAppversion?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xAppid?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xDeviceos?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xUserType?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xPhonemake?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xPhonemodel?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xPushtokentype?: string

    /**
     * 
     * @type {string}
     * @memberof TransportApiGetTransportEstimate
     */
    readonly xSessionId?: string
}

/**
 * TransportApi - object-oriented interface
 * @export
 * @class TransportApi
 * @extends {BaseAPI}
 */
export class TransportApi extends BaseAPI {
    /**
     * cancel booking
     * @summary Cancel booking
     * @param {TransportApiCancelBookingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransportApi
     */
    public cancelBooking(requestParameters: TransportApiCancelBookingRequest, options?: AxiosRequestConfig) {
        return TransportApiFp(this.configuration).cancelBooking(requestParameters.bookingId, requestParameters.cancelReasonId, requestParameters.xPlatform, requestParameters.gojekCountryCode, requestParameters.xUniqueid, requestParameters.xAppversion, requestParameters.xAppid, requestParameters.xDeviceos, requestParameters.xUserType, requestParameters.xPhonemake, requestParameters.xPhonemodel, requestParameters.xPushtokentype, requestParameters.xSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET dropoff spots
     * @param {TransportApiGetDropoffSpotsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransportApi
     */
    public getDropoffSpots(requestParameters: TransportApiGetDropoffSpotsRequest, options?: AxiosRequestConfig) {
        return TransportApiFp(this.configuration).getDropoffSpots(requestParameters.location, requestParameters.serviceType, requestParameters.xPlatform, requestParameters.gojekCountryCode, requestParameters.xUniqueid, requestParameters.xAppversion, requestParameters.xAppid, requestParameters.xDeviceos, requestParameters.xUserType, requestParameters.xPhonemake, requestParameters.xPhonemodel, requestParameters.xPushtokentype, requestParameters.xSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET pickup spots
     * @param {TransportApiGetPickupSpotsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransportApi
     */
    public getPickupSpots(requestParameters: TransportApiGetPickupSpotsRequest, options?: AxiosRequestConfig) {
        return TransportApiFp(this.configuration).getPickupSpots(requestParameters.location, requestParameters.serviceType, requestParameters.source, requestParameters.xPlatform, requestParameters.gojekCountryCode, requestParameters.xUniqueid, requestParameters.xAppversion, requestParameters.xAppid, requestParameters.xDeviceos, requestParameters.xUserType, requestParameters.xPhonemake, requestParameters.xPhonemodel, requestParameters.xPushtokentype, requestParameters.xSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET transport estimate
     * @param {TransportApiGetTransportEstimateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransportApi
     */
    public getTransportEstimate(requestParameters: TransportApiGetTransportEstimateRequest, options?: AxiosRequestConfig) {
        return TransportApiFp(this.configuration).getTransportEstimate(requestParameters.sendPrioritisedOrder, requestParameters.userSelectedServiceType, requestParameters.waypoints, requestParameters.xPlatform, requestParameters.gojekCountryCode, requestParameters.xUniqueid, requestParameters.xAppversion, requestParameters.xAppid, requestParameters.xDeviceos, requestParameters.xUserType, requestParameters.xPhonemake, requestParameters.xPhonemodel, requestParameters.xPushtokentype, requestParameters.xSessionId, options).then((request) => request(this.axios, this.basePath));
    }
}


