<?php
/**
 * GoidTokenDataTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  GoIdGojekPhp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * goid.gojekapi.com
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GoIdGojekPhp\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GoidTokenDataTest Class Doc Comment
 *
 * @category    Class
 * @description GoidTokenData
 * @package     GoIdGojekPhp
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GoidTokenDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GoidTokenData"
     */
    public function testGoidTokenData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "otp"
     */
    public function testPropertyOtp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "otp_token"
     */
    public function testPropertyOtpToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
